from __future__ import annotations
"""
AHRAS Alert Intelligence Models
================================
Formal data models for the Alert Intelligence Layer.
Defines atomic RawAlerts, ExposureMetrics, IncidentClusters, and TriageDecisions.
All models strictly maintain tamper-evident evidence references (evidence_ids)
to guarantee full provenance tracing to the cryptographic EvidenceLedger.
"""

import time
import uuid
from enum import Enum
from typing import Any, Dict, List, Optional, Set
from pydantic import BaseModel, Field


class TriageLevel(str, Enum):
    CRITICAL = "CRITICAL"
    HIGH     = "HIGH"
    MEDIUM   = "MEDIUM"
    LOW      = "LOW"
    INFO     = "INFO"


class NetworkZone(str, Enum):
    INTERNET_FACING = "INTERNET_FACING"
    DMZ             = "DMZ"
    INTERNAL_PROD   = "INTERNAL_PROD"
    CORPORATE_LAN   = "CORPORATE_LAN"
    ISOLATED_SECURE = "ISOLATED_SECURE"


class RawAlert(BaseModel):
    """
    Atomic alert generated by an upstream detection engine.
    Carries source detector type, entity keys, raw/normalized scores,
    MITRE taxonomy, and cryptographic evidence IDs.
    """
    alert_id: str = Field(default_factory=lambda: f"ALT-{uuid.uuid4().hex[:12]}")
    event_id: str
    entity_key: str                     # Primary entity (e.g. "host:srv-db-01", "ip:192.168.1.100")
    source_engine: str                  # "signature", "ml_anomaly", "statistical", "tgnn", "encrypted_session"
    detector_name: str
    severity: str                       # "CRITICAL", "HIGH", "MEDIUM", "LOW"
    raw_score: float
    normalized_score: float             # [0.0, 1.0]
    confidence: float                   # [0.0, 1.0]
    uncertainty: float = 0.0            # [0.0, 1.0]
    mitre_tactic: Optional[str] = None  # e.g. "TA0001" (Initial Access)
    mitre_technique: Optional[str] = None # e.g. "T1190" (Exploit Public-Facing Application)
    timestamp: float = Field(default_factory=time.time)
    evidence_ids: List[str] = Field(default_factory=list) # Pointer to cryptographic ledger
    metadata: Dict[str, Any] = Field(default_factory=dict)
    suppressed_count: int = 0           # Count of deduplicated occurrences folded into this alert


class ExposureMetric(BaseModel):
    """
    Asset and network vulnerability exposure metrics used to contextualize risk.
    """
    entity_key: str
    network_zone: NetworkZone = NetworkZone.INTERNAL_PROD
    asset_criticality_tier: int = 2     # Tier 1 (Crown Jewels, e.g. DC/DB), Tier 2 (App), Tier 3 (Workstations)
    is_internet_exposed: bool = False
    open_cves: List[str] = Field(default_factory=list)
    max_cve_cvss: float = 0.0           # [0.0, 10.0]
    business_impact_score: float = 0.5  # [0.0, 1.0]


class IncidentCluster(BaseModel):
    """
    Correlated multi-stage security incident representing a synthesized threat campaign.
    Aggregates related RawAlerts across space (entities) and time (kill-chain progression).
    """
    cluster_id: str = Field(default_factory=lambda: f"INC-{uuid.uuid4().hex[:10]}")
    title: str
    entity_keys: List[str] = Field(default_factory=list)
    primary_entity: str
    start_time: float
    last_update_time: float
    alerts: List[RawAlert] = Field(default_factory=list)
    tactics_present: List[str] = Field(default_factory=list)
    techniques_present: List[str] = Field(default_factory=list)
    evidence_ids: List[str] = Field(default_factory=list)
    
    # Priority & Exposure
    exposure_score: float = 0.0         # Calibrated exposure [0.0, 1.0]
    progression_score: float = 0.0      # Multi-stage kill chain depth [0.0, 1.0]
    aggregate_risk: float = 0.0         # Synthesized risk score [0.0, 1.0]
    priority_score: float = 0.0         # Final triage priority score [0.0, 1.0]
    triage_level: TriageLevel = TriageLevel.LOW
    
    # Operational Status
    status: str = "OPEN"                # "OPEN", "INVESTIGATING", "CONTAINED", "CLOSED"
    assigned_analyst: Optional[str] = None
    recommended_action: str = "MONITOR"
    explanation_summary: str = ""

    def add_alert(self, alert: RawAlert) -> None:
        """Adds an alert to the cluster and updates spatial/temporal bounds and evidence pointers."""
        self.alerts.append(alert)
        if alert.entity_key not in self.entity_keys:
            self.entity_keys.append(alert.entity_key)
        if alert.mitre_tactic and alert.mitre_tactic not in self.tactics_present:
            self.tactics_present.append(alert.mitre_tactic)
        if alert.mitre_technique and alert.mitre_technique not in self.techniques_present:
            self.techniques_present.append(alert.mitre_technique)
        for ev_id in alert.evidence_ids:
            if ev_id not in self.evidence_ids:
                self.evidence_ids.append(ev_id)
        if alert.timestamp > self.last_update_time:
            self.last_update_time = alert.timestamp


class TriageDecision(BaseModel):
    """
    Actionable triage determination for SOC dispatch or autonomous containment.
    """
    cluster_id: str
    triage_level: TriageLevel
    priority_score: float
    recommended_action: str
    rationale: str
    mitre_coverage_summary: Dict[str, List[str]] # {"tactics": [...], "techniques": [...]}
    evidence_count: int
    blast_radius_estimate: float
