from __future__ import annotations
"""
AHRAS Module — Shadow Model Promotion & Safety Pipeline (Section 25 / Research Frontier P1)
--------------------------------------------------------------------------------------------
Implements the formal multi-stage model evaluation and promotion lifecycle:

    TRAIN -> VALIDATE -> SHADOW -> COMPARE -> SAFETY CHECK -> PROMOTE / ROLLBACK

Evaluation Gates:
  1. Detection Performance: Candidate F1 >= Champion F1 - delta_F1 (default delta = 0.01)
  2. False Positive Resistance: Candidate FPR <= Champion FPR + delta_FPR (default delta = 0.015)
  3. Unknown/Zero-Day Detection: Candidate OOD Recall >= min_ood_recall (default = 0.85)
  4. Calibration Integrity: Expected Calibration Error (ECE) <= 0.15, Brier Score <= 0.20
  5. XAI Rank Stability: Jaccard feature-attribution stability >= 0.80 under Gaussian perturbation
  6. Operational SLA: P95 Latency <= max_p95_ms (default = 25.0 ms)
  7. Computational Budget: Memory growth <= 150%, CPU cost growth <= 150%
  8. MITRE ATT&CK Coverage: Candidate technique coverage >= Champion coverage
  9. Prequential Drift Stability: Page-Hinkley cumulative score <= drift_alarm_threshold
"""

import copy
import enum
import logging
import math
import threading
import time
import uuid
from dataclasses import asdict, dataclass, field
from typing import Any, Dict, List, Optional, Tuple

import numpy as np

log = logging.getLogger(__name__)


class PromotionStatus(str, enum.Enum):
    PENDING = "PENDING"
    IN_SHADOW = "IN_SHADOW"
    PROMOTED = "PROMOTED"
    REJECTED = "REJECTED"
    ROLLED_BACK = "ROLLED_BACK"


@dataclass
class ModelEvaluationMetrics:
    """Standardized performance and operational scorecard for a candidate or champion model."""
    model_name: str
    version: str
    f1_score: float
    precision: float
    recall: float
    fpr: float
    unknown_ood_recall: float
    ece_calibration: float
    brier_score: float
    xai_stability_jaccard: float
    p50_latency_ms: float
    p95_latency_ms: float
    memory_mb: float
    cpu_cost_factor: float
    mitre_technique_coverage: int
    drift_statistic: float


@dataclass
class PromotionGateCheck:
    gate_name: str
    passed: bool
    champion_value: float
    candidate_value: float
    threshold_condition: str
    margin: float
    details: str = ""


@dataclass
class PromotionDecision:
    """Formal audit decision generated by the safety check comparison."""
    decision_id: str
    candidate_name: str
    candidate_version: str
    champion_name: str
    champion_version: str
    status: PromotionStatus
    all_gates_passed: bool
    passed_gate_count: int
    total_gate_count: int
    gate_checks: List[PromotionGateCheck] = field(default_factory=list)
    rejection_reasons: List[str] = field(default_factory=list)
    timestamp: float = field(default_factory=time.time)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "decision_id": self.decision_id,
            "candidate": f"{self.candidate_name}:{self.candidate_version}",
            "champion": f"{self.champion_name}:{self.champion_version}",
            "status": self.status.value,
            "all_gates_passed": self.all_gates_passed,
            "passed_gate_count": self.passed_gate_count,
            "total_gate_count": self.total_gate_count,
            "gate_checks": [asdict(g) for g in self.gate_checks],
            "rejection_reasons": self.rejection_reasons,
            "timestamp": self.timestamp,
        }


@dataclass
class PromotionPolicy:
    """Configurable invariant thresholds for candidate promotion."""
    max_f1_degradation: float = 0.010
    max_fpr_increase: float = 0.015
    min_unknown_ood_recall: float = 0.850
    max_allowed_ece: float = 0.150
    max_allowed_brier: float = 0.220
    min_xai_stability: float = 0.750
    max_p95_latency_ms: float = 25.00
    max_memory_growth_ratio: float = 1.50
    require_coverage_non_decreasing: bool = True
    max_drift_statistic: float = 50.0


class ShadowModelPromotionPipeline:
    """
    Manages shadow deployment, cross-model comparison, and deterministic promotion gating.
    """

    def __init__(self, policy: Optional[PromotionPolicy] = None) -> None:
        self.policy = policy or PromotionPolicy()
        self._lock = threading.RLock()
        self._champion: Optional[ModelEvaluationMetrics] = None
        self._shadow_candidates: Dict[str, ModelEvaluationMetrics] = {}
        self._decision_history: List[PromotionDecision] = []

    def register_champion(self, metrics: ModelEvaluationMetrics) -> None:
        """Sets the baseline champion model metrics."""
        with self._lock:
            self._champion = copy.deepcopy(metrics)
            log.info(f"Registered active champion model: {metrics.model_name}:{metrics.version} (F1={metrics.f1_score:.4f})")

    def enroll_shadow_candidate(self, metrics: ModelEvaluationMetrics) -> None:
        """Enrolls a newly trained candidate into shadow evaluation state."""
        with self._lock:
            key = f"{metrics.model_name}:{metrics.version}"
            self._shadow_candidates[key] = copy.deepcopy(metrics)
            log.info(f"Enrolled shadow candidate: {key}")

    def evaluate_promotion(
        self,
        candidate_key: str,
        champion_override: Optional[ModelEvaluationMetrics] = None,
    ) -> PromotionDecision:
        """
        Executes formal 9-gate safety check comparing candidate against active champion.
        """
        with self._lock:
            champion = champion_override or self._champion
            if champion is None:
                raise ValueError("Cannot evaluate candidate: No active champion model registered.")

            if candidate_key not in self._shadow_candidates:
                raise KeyError(f"Candidate {candidate_key} not found in shadow registry.")
            candidate = self._shadow_candidates[candidate_key]

            decision_id = f"prom-{uuid.uuid4().hex[:8]}"
            gate_checks: List[PromotionGateCheck] = []
            rejections: List[str] = []

            # Gate 1: F1 Score non-degradation
            f1_diff = candidate.f1_score - champion.f1_score
            g1_pass = f1_diff >= -self.policy.max_f1_degradation
            gate_checks.append(
                PromotionGateCheck(
                    gate_name="Detection_F1_NonDegradation",
                    passed=g1_pass,
                    champion_value=champion.f1_score,
                    candidate_value=candidate.f1_score,
                    threshold_condition=f"candidate >= champion - {self.policy.max_f1_degradation}",
                    margin=f1_diff,
                    details=f"Candidate F1: {candidate.f1_score:.4f}, Champion: {champion.f1_score:.4f}",
                )
            )
            if not g1_pass:
                rejections.append(f"F1 degradation exceeded limit: {f1_diff:.4f} < -{self.policy.max_f1_degradation}")

            # Gate 2: FPR increase control
            fpr_diff = candidate.fpr - champion.fpr
            g2_pass = fpr_diff <= self.policy.max_fpr_increase
            gate_checks.append(
                PromotionGateCheck(
                    gate_name="False_Positive_Rate_Control",
                    passed=g2_pass,
                    champion_value=champion.fpr,
                    candidate_value=candidate.fpr,
                    threshold_condition=f"candidate <= champion + {self.policy.max_fpr_increase}",
                    margin=fpr_diff,
                    details=f"Candidate FPR: {candidate.fpr:.4f}, Champion: {champion.fpr:.4f}",
                )
            )
            if not g2_pass:
                rejections.append(f"FPR increase exceeded limit: +{fpr_diff:.4f} > {self.policy.max_fpr_increase}")

            # Gate 3: Unknown / OOD detection recall
            g3_pass = candidate.unknown_ood_recall >= self.policy.min_unknown_ood_recall
            gate_checks.append(
                PromotionGateCheck(
                    gate_name="Unknown_OOD_Recall",
                    passed=g3_pass,
                    champion_value=champion.unknown_ood_recall,
                    candidate_value=candidate.unknown_ood_recall,
                    threshold_condition=f"candidate >= {self.policy.min_unknown_ood_recall}",
                    margin=candidate.unknown_ood_recall - self.policy.min_unknown_ood_recall,
                    details=f"Candidate OOD Recall: {candidate.unknown_ood_recall:.4f}",
                )
            )
            if not g3_pass:
                rejections.append(f"Unknown attack recall insufficient: {candidate.unknown_ood_recall:.4f} < {self.policy.min_unknown_ood_recall}")

            # Gate 4: Calibration ECE
            g4_pass = candidate.ece_calibration <= self.policy.max_allowed_ece
            gate_checks.append(
                PromotionGateCheck(
                    gate_name="Expected_Calibration_Error",
                    passed=g4_pass,
                    champion_value=champion.ece_calibration,
                    candidate_value=candidate.ece_calibration,
                    threshold_condition=f"candidate <= {self.policy.max_allowed_ece}",
                    margin=self.policy.max_allowed_ece - candidate.ece_calibration,
                    details=f"Candidate ECE: {candidate.ece_calibration:.4f}",
                )
            )
            if not g4_pass:
                rejections.append(f"Calibration ECE too high: {candidate.ece_calibration:.4f} > {self.policy.max_allowed_ece}")

            # Gate 5: XAI Stability
            g5_pass = candidate.xai_stability_jaccard >= self.policy.min_xai_stability
            gate_checks.append(
                PromotionGateCheck(
                    gate_name="XAI_Rank_Stability",
                    passed=g5_pass,
                    champion_value=champion.xai_stability_jaccard,
                    candidate_value=candidate.xai_stability_jaccard,
                    threshold_condition=f"candidate >= {self.policy.min_xai_stability}",
                    margin=candidate.xai_stability_jaccard - self.policy.min_xai_stability,
                    details=f"Candidate XAI Stability: {candidate.xai_stability_jaccard:.4f}",
                )
            )
            if not g5_pass:
                rejections.append(f"XAI explanation stability below threshold: {candidate.xai_stability_jaccard:.4f} < {self.policy.min_xai_stability}")

            # Gate 6: Operational SLA P95 Latency
            g6_pass = candidate.p95_latency_ms <= self.policy.max_p95_latency_ms
            gate_checks.append(
                PromotionGateCheck(
                    gate_name="P95_Latency_SLA",
                    passed=g6_pass,
                    champion_value=champion.p95_latency_ms,
                    candidate_value=candidate.p95_latency_ms,
                    threshold_condition=f"candidate <= {self.policy.max_p95_latency_ms} ms",
                    margin=self.policy.max_p95_latency_ms - candidate.p95_latency_ms,
                    details=f"Candidate P95 Latency: {candidate.p95_latency_ms:.2f} ms",
                )
            )
            if not g6_pass:
                rejections.append(f"P95 latency SLA breached: {candidate.p95_latency_ms:.2f}ms > {self.policy.max_p95_latency_ms}ms")

            # Gate 7: Memory Growth Ratio
            mem_ratio = candidate.memory_mb / max(0.1, champion.memory_mb)
            g7_pass = mem_ratio <= self.policy.max_memory_growth_ratio
            gate_checks.append(
                PromotionGateCheck(
                    gate_name="Memory_Footprint_Growth",
                    passed=g7_pass,
                    champion_value=champion.memory_mb,
                    candidate_value=candidate.memory_mb,
                    threshold_condition=f"growth_ratio <= {self.policy.max_memory_growth_ratio}",
                    margin=self.policy.max_memory_growth_ratio - mem_ratio,
                    details=f"Candidate Memory: {candidate.memory_mb:.1f}MB, Champion: {champion.memory_mb:.1f}MB",
                )
            )
            if not g7_pass:
                rejections.append(f"Memory footprint growth ratio exceeded: {mem_ratio:.2f}x > {self.policy.max_memory_growth_ratio}x")

            # Gate 8: MITRE Coverage Non-Decreasing
            cov_diff = candidate.mitre_technique_coverage - champion.mitre_technique_coverage
            g8_pass = cov_diff >= 0 if self.policy.require_coverage_non_decreasing else True
            gate_checks.append(
                PromotionGateCheck(
                    gate_name="MITRE_ATTACK_Coverage",
                    passed=g8_pass,
                    champion_value=float(champion.mitre_technique_coverage),
                    candidate_value=float(candidate.mitre_technique_coverage),
                    threshold_condition="candidate >= champion",
                    margin=float(cov_diff),
                    details=f"Candidate covers {candidate.mitre_technique_coverage} techniques, Champion covers {champion.mitre_technique_coverage}",
                )
            )
            if not g8_pass:
                rejections.append(f"MITRE coverage decreased by {-cov_diff} techniques")

            # Gate 9: Prequential Drift Statistic
            g9_pass = candidate.drift_statistic <= self.policy.max_drift_statistic
            gate_checks.append(
                PromotionGateCheck(
                    gate_name="Prequential_Drift_Stability",
                    passed=g9_pass,
                    champion_value=champion.drift_statistic,
                    candidate_value=candidate.drift_statistic,
                    threshold_condition=f"candidate <= {self.policy.max_drift_statistic}",
                    margin=self.policy.max_drift_statistic - candidate.drift_statistic,
                    details=f"Candidate Drift Stat: {candidate.drift_statistic:.2f}",
                )
            )
            if not g9_pass:
                rejections.append(f"Drift statistic alarmed: {candidate.drift_statistic:.2f} > {self.policy.max_drift_statistic}")

            all_passed = all(g.passed for g in gate_checks)
            status = PromotionStatus.PROMOTED if all_passed else PromotionStatus.REJECTED

            decision = PromotionDecision(
                decision_id=decision_id,
                candidate_name=candidate.model_name,
                candidate_version=candidate.version,
                champion_name=champion.model_name,
                champion_version=champion.version,
                status=status,
                all_gates_passed=all_passed,
                passed_gate_count=sum(1 for g in gate_checks if g.passed),
                total_gate_count=len(gate_checks),
                gate_checks=gate_checks,
                rejection_reasons=rejections,
            )

            if all_passed:
                # Promotion: Candidate becomes new champion
                self._champion = copy.deepcopy(candidate)
                log.info(f"Promoted candidate {candidate_key} to active champion!")

            self._decision_history.append(decision)
            return decision
